name = "puppyblog"
license = "MIT"
licenselink = "https://github.com/puppycodes/puppycodes/blob/master/LICENSE.md"
description = "woof!"
homepage = "https://puppy.codes"
tags = ["blog", "security"]
features = ["blog"]
min_version = 0.1

[author]
  name = "puppycodes"
  homepage = "https://github.com/puppycodes"
